version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    environment:
      BACKEND_URL: backend:3070
    ports:
      - "8080:80"
    links:
      - "backend"

  backend:
    build:
      dockerfile: Dockerfile.backend
    environment:
      DB_URL: db
      DB_USERNAME: root
      DB_PASSWORD: example
    ports:
      - "3070:3007"
    links:
      - "db"

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
