apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: invenfinder
spec:
  serviceName: db
  replicas: 2
  selector:
    matchLabels:
      function: db
  template:
    metadata:
      labels:
        app: invenfinder
        function: db
    spec:
      containers:
        - image: mariadb
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mariadb-password
          ports:
          - containerPort: 3306
            name: web
          volumeMounts:
          - name: db
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invenfinder
    function: db
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    function: db
