apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    app: invenfinder
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:  # This should be a remote storage if deploying on multiple nodes
    path: /data/db
