apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 2
  selector:
    matchLabels:
      function: db
  template:
    metadata:
      labels:
        app: invenfinder
        function: db
    spec:
      containers:
      - name: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: example
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: db
          mountPath: /mnt/db
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invenfinder
    function: db
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    function: db
