apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    app: invenfinder
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"